FROM alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

# renovate: datasource=repology depName=alpine_3_23_3/openssh versioning=loose
ENV OPENSSH_VERSION=10.2_p1-r0
# renovate: datasource=repology depName=alpine_3_23_3/openssh-sftp-server versioning=loose
ENV OPENSSH_SFTP_SERVER_VERSION=10.2_p1-r0

RUN apk add openssh=${OPENSSH_VERSION} openssh-sftp-server=${OPENSSH_SFTP_SERVER_VERSION} && \
    adduser -D vela -h /home/vela && \
    echo -n "vela:hunter2" | chpasswd && \
    mkdir -p /home/vela/.ssh/ && \
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC76zDdM8ufzSIy9FRNtnnRh2vl93tmYCtyHH24b8fGyp6DI8ArtCu9muEsRNGB+zwqyMxSWoXhnJkpwQ3Jtc3vHs3IZZGB7UNNHxzOj1wHeU2o+jcUGbl6fANSa6G2GATTXE+e568L65dnE73tUjihtCpK5WYXraa9l61kg82Jfw==" > /home/vela/.ssh/authorized_keys && \
    adduser -D alev -h /home/alev && \
    echo -n "alev:2retnuh" | chpasswd

ENTRYPOINT ["/usr/sbin/sshd", "-D", "-e"]
