# Copyright (c) 2022 Target Brands, Inc. All rights reserved.
#
# Use of this source code is governed by the LICENSE file in this repository.

###############################################################
##     docker build --no-cache -t vela-ssh:local .     ##
###############################################################

FROM alpine:latest

RUN apk add --update --no-cache ca-certificates openssh sshpass

COPY release/vela-ssh /bin/vela-ssh

ENTRYPOINT ["/bin/vela-ssh"]
