# name of the action
name: publish

# trigger on push events with branch main
on:
  push:
    branches: [ main ]

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: clone
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        # ensures we fetch tag history for the repository
        fetch-depth: 0

    - name: install go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        # use version from go.mod file
        go-version-file: 'go.mod'
        cache: true
        check-latest: true

    - name: build
      env:
        GOOS: linux
        CGO_ENABLED: '0'
      run: |
        make build-static-ci

    - name: grab dependency versions from makefile
      run: |
        grep "^OPENSSH.*=" Makefile >> $GITHUB_ENV
        grep "^SSHPASS_VERSION.*=" Makefile >> $GITHUB_ENV

    - name: publish scp
      uses: elgohr/Publish-Docker-Github-Action@eb53b3ec07136a6ebaed78d8135806da64f7c7e2 # v5
      with:
        name: target/vela-scp
        cache: true
        dockerfile: Dockerfile.scp
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: OPENSSH_VERSION,SSHPASS_VERSION

    - name: publish ssh
      uses: elgohr/Publish-Docker-Github-Action@eb53b3ec07136a6ebaed78d8135806da64f7c7e2 # v5
      with:
        name: target/vela-ssh
        cache: true
        dockerfile: Dockerfile.ssh
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: OPENSSH_VERSION,SSHPASS_VERSION
