# name of the action
name: publish

# trigger on push events with branch main
on:
  push:
    branches: [ main ]

# pipeline to execute
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: golang:1.18
    steps:
    - name: clone
      uses: actions/checkout@v3
      with:
        # ensures we fetch tag history for the repository
        fetch-depth: 0

    - name: build
      env:
        GOOS: linux
        CGO_ENABLED: '0'
      run: |
        make build-static-ci

    - name: grab dependency versions from makefile
      run: |
        grep "^OPENSSH.*=" Makefile >> $GITHUB_ENV
        grep "^SSHPASS_VERSION.*=" Makefile >> $GITHUB_ENV

    - name: publish scp
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: target/vela-scp
        cache: true
        dockerfile: Dockerfile.scp
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: OPENSSH_VERSION,SSHPASS_VERSION

    - name: publish ssh
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: target/vela-ssh
        cache: true
        dockerfile: Dockerfile.ssh
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: OPENSSH_VERSION,SSHPASS_VERSION
